log_directories = {
    'ASPNET/UI': {
        'description': 'Logs related to the user interface and administration of Archive Store.',
        'files': {
            'Admin_archivestores_aspx.log': 'Debug log file for the archive store page seen by administrators.',
            'Admin_rulebasedarchiving_aspx.log': 'Debug log file created when the Rule-Based Archiving is configured.',
            'Admin_usercontrols_archivestore_archivestoreschedule_ascx.log': 'Debug log file setting up the interval for archivestoremanagement.',
            'AdvanceSearch.log': 'Debug log file for the Advanced search page.',
            'Archive.log': 'Contains information about the Archive Stores configuration page.',
            'ArchiveStoreDetail.log': 'Contains information about actions performed on the Archive Stores, such as add, remove, and swap dates.',
            'ArchiveStores.log': 'Contains information about actions performed on the Archive Stores, such as add, remove, and swap dates.',
            'ArchiveStoresHelper.log': 'Contains information about determining the current archive store.',
            'ArchiveStoreSummary.log': 'Contains information requested for the Archive Store Summary page.',
            'ArchiveStoresWizard.log': 'Contains information about the settings configured when running through the Archive Store wizard.',
            'ArchivingScope.log': 'Debug log file for when the Archiving Scope page is loaded.',
            'AuditingSettingsWizard.log': 'Debug log generated when settings are changed for the Auditing configuration using the Audit Settings Wizard.',
            'AuditWrapper.log': 'Debug log file for the AuditWrapper – the module which provides auditing of the actions which can be performed from the MARC UI.',
            'CSClient*.log': 'Configuration services WCF client logging.',
            'CSDatabases.log': 'Debug log file for module responsible for finding matching databases based off of timestamp/date.',
            'EcomHelper.log': 'Contains logging about information fetched from the registry for notification purposes.',
            'LicenseHelper.log': 'Logging for helper for the ecom licensing module.',
            'MAIN.log': 'General debug log.',
            'MainMaster.log': 'Logging for general information about UI, retrieval of registry values, notification, eval status, and authentication method.',
            'FolderStructureRetrieval.log': 'The debug log for the Folder Structure Retrieval menu.',
            'FolderStructureRetrievalWizard.log': 'Log for setting up folder structure retrieval.',
            'GeneralSettings.log': 'Log for the General Settings page.',
            'GFI.Common.Tracing.log': 'Common debug log written by the gfi_log module.',
            'MailboxList.log': 'Debug log file for the mailboxes added to the Archive page.',
            'MailHelper.log': 'Debug log file for the helper module used to find all folders for a given mailbox.',
            'MailServers.log': 'Debug log file setup to datasource for journaling mailbox.',
            'MailServerWizard.log': 'Debug log file for the wizard used to connect to the journaling datasource.',
            'Messagebody.log': 'Debug log file for the page which is used to show the message body to the user.',
            'Messagesource.log': 'Debug log file for the page which is used to save the email to disk.',
            'Messageview.log': 'Debug log file for the page which is used to display the message to the user.',
            'PostInstallWizard.log': 'Log for the install wizard during post installation.',
            'OutlookConnector.log': 'Debug log file showing info as to when the Outlook Connector page is displayed in the UI.',
            'ProfileProvider.log': 'Debug log file for the module which is used to provide information from the profile of the authenticated user.',
            'RetentionPolicies.log': 'Log file for configuration of retention policies in the UI.',
            'Searchresults.log': 'Debug log file for the .aspx page which loads the search results and shows them to the user.',
            'TellMeMore.log': 'Debug log for the TellMeMore link within the UI.',
            'UIControlHelper.log': 'Debug log file for the loading and compiling of transforms used in the UI.',
            'UIPerformance.log': 'Debug log for Ajax configuration pages.',
            'WebCS.log': 'Debug log file for a helper module.',
            'WebCulture.log': 'Debug log file used for the localization of MARC.',
            'WebHelper.log': 'Debug log file for a module which provides various helper functions used in the front end.',
            'WebLoader.log': 'Debug log file for the module which initializes the components required by the web application when a user accesses it.',
            'WebLoaderSplash.log': 'Debug log file for the initial splash screen upon opening the UI.',
            'WebLocalization.log': 'Debug log file for the module which allows the MARC interface to be displayed in different languages.',
            'WSOutlook.log': 'Debug log file for the web service that is used by the Outlook Connector.',
            'WSOutlook_Dump.log': 'Debug log file for the web service that is used by the Outlook Connector showing details about each transaction.',
            'WSSearch.log': 'Debug log file for the search web service.',
            'WSSend.log': 'Debug log file for the web service that is used to create the emails when the user selects to restore an email to an email address. The email will be saved to the Pickup folder.',
            'WSStore.log': 'Debug log file for the web service that is used to list the Archive Stores.'
        }
    },
    'ASPNET/Services': {
        'description': 'Logs related to ASP.NET services used by Archiver.',
        'files': {
            'ArchiveAssistant.log': 'Debug log for communication with the Archive Assistant.',
            'LoaderModule.log': 'Debug log file for loading of the remoting configuration.',
            'ManualArchiving.log': 'Debug log file for the process of archiving email or folders manually.',
            'StoreHelper.log': 'Debug log file indicating the process of receiving the hash/SIS ID and if the email already exists.'
        }
    },
    'BulkSchemaUpgrader': {
        'description': 'Logs related to bulk schema upgrades in Archiver.',
        'files': {
            'CSCache.log': 'Debug log file of the module which caches configuration data.',
            'GFIArchiverBulkSchemaUpgrader.log': 'Debug log file for the MARC BulkSchemaUpgrader.',
            'LocalizationProvider.log': 'Debug log file for the module which provides localization support in the BulkSchemaUpgrader.'
        }
    },
    'core': {
        'description': 'Core services logs related to authentication, configuration, and service management.',
        'files': {
            'AdaAuthentication.log': 'Debug log file for the module which checks the information on the logged on user, and provides this information to the other modules so that the correct data is shown to the user e.g. if the configuration tab is shown, or that only the user’s emails are retrieved from the database. Used by RBAC as well.',
            'AdaCache.log': 'Debug log file of the module which maintains a cache of information retrieved from AD by ADA.',
            'AdaConfigurationM.log': 'Debug log file for the module which is used to read user information from the MARC configuration relating to authentication and Roles and Permissions.',
            'AdaConfigurationR.log': 'Same as AdaConfigurationL.log, however the R in the filename signifies that the module was used by modules in other processes.',
            'AdaInformation.log': 'Debug log file for the module which retrieves information from AD whenever it is required.',
            'AdaSink.log': 'Log file for the sink which is installed into Remoting to intercept and authenticate Remoting calls.',
            'AttendantService.log': 'Log file for the MARC Attendant service. This will show the loading and unloading of the various Attendant modules.',
            'Checklicdd.txt': 'Debug log file for the module that checks the MARC license. Lists the licensed users and the number of elapsed evaluation days. Useful for troubleshooting licensing problems.',
            'Checklic.log': 'Debug log file for the module which checks the license and the evaluation properties.',
            'ConfigurationServices.log': 'Debug log file for the Configuration Services module – the module which provides an interface to the main MARC configuration file – marcsettings.xml.',
            'ConfigurationServices_vss.log': 'Debug log file for the Configuration Services interfacing with VSS.',
            'CSCache.log': 'Debug log file of the module which caches configuration data.',
            'CSHolderLicensing.log': 'Debug log file of the module which caches configuration data related to licensing.',
            'CSHolderLogging.log': 'Debug log file of the module which caches configuration data.',
            'DirectoryEngineAD.log': 'Log file of the module used when querying AD for user information.',
            'EWSProvider.log': 'Debug log file for a mailbox connected via EWS.',
            'EWSProviderTest.log': 'Debug log file for attempts to connect a mailbox using EWS.',
            'GFI.Common.Tracing.log': 'Common debug log written by the gfi_log module.',
            'ImapProvider.log': 'Debug log file for a mailbox connected via IMAP.',
            'ImapProviderTest.log': 'Debug log file for attempts to connect a mailbox using IMAP.',
            'LicensingNotifications.log': 'Debug log file for the module which checks if any licensing related notifications should be sent to the Administrator.',
            'LogFilters.log': 'Debug log file of the module which loads the filters used by LogScheduler to process the message before they are saved in the DLE cache files.',
            'LogScheduler.log': 'Debug log file for the module which initiates the logging of emails to the DLE cache files.',
            'LogSubmit2.log': 'Debug log file for the LogSubmit2 module – the module which is loaded by LogScheduler and used to perform the logging of the emails to the database, using Store ->DLEAgent.',
            'NotificationServices.log': 'Debug log file for the Notification Services – used whenever a notification is created, which will be sent by the SMTPSend module.',
            'RCInfo.log': 'Debug log file for the module which provides licensing related information to the configuration.',
            'Regcount34.gfi_log.txt': 'Debug log file that logs information from the Attendant service.',
            'RegcountPlugin.log': 'Debug log file of the module starting the regcount24 module.',
            'RemotingPlugin.log': 'Debug log file for the Remoting module – the module which initiates the Remoting ‘services’.',
            'SMTPSend.log': 'Debug log file for the SMTPSend module – the module which sends any emails found in the Pickup folder.',
            'TicketServices.log': 'Debug log file for the TicketServices module – the module used to assign tickets to emails which have been exported using the bulk export tool.',
            'UAutoDisc.log': 'Debug log file used by an EWS UMPolling process which detects the best available Microsoft Exchange ClientAccess server.',
            'UMPoll.ComuteHash.log': 'Debug log file for the UMPolling module which computes the hash for the emails which are retrieved from the users’ mailboxes.',
            'UMPoll.EWSPoll.log': 'Debug log file for the executable which is spawned by UMPolling (EWS) and which downloads emails from Microsoft Exchange for user mailbox polling functionality.',
            'UMPoll.EWSPollTest.log': 'Debug log file for the executable which is spawned by UMRemote (EWS) and which is used to test the connection to the Microsoft Exchange for user mailbox polling functionality.',
            'UMPoll.ExPoll.log': 'Debug log file for the executable which is spawned by UMPolling (MAPI) and which downloads emails from Microsoft Exchange for user mailbox polling functionality.',
            'UMPoll.ExPollTest.log': 'Debug log file for the executable which is spawned by UMRemote (MAPI) and which is used to test the connection to the Microsoft Exchange for user mailbox polling functionality.',
            'UMPoll.log': 'Debug log file for the UMPolling module.',
            'UMPollRem.log': 'Debug log file for the UMPollRemote Remoting module.',
            'Usercntmaad.txt': 'Debug log file used to count users from AD and used for licensing purposes.',
            'Usertimecnt.txt': 'Debug log file of the module which checks how long MARC has been installed - used for licensing purposes.',
            'VssWriterSubscriber.log': 'Debug log file for the VSSWriterSubscriber module loaded by the Core service.'
        }
    },
    'IMAP': {
        'description': 'Logs related to IMAP processes in Archiver.',
        'files': {
            'AdaAuthentication.log': 'Debug log file for the module which provides an authentication mechanism for ADA with AD.',
            'AdaCache.log': 'Debug log file of the module which maintains a cache of information retrieved from AD by ADA.',
            'AdaConfigurationR.log': 'Debug log file for the module which is used to read user information from the MARC configuration e.g. the users who have full access to the emails stored by MARC, group managers, and User Access Control.',
            'AdaInformation.log': 'Debug log file of the module used to retrieve information from AD.',
            'Adapter.log': 'Debug log file for the actions taken from the client. Can see who logged on and the headers being retrieved.',
            'AdaSink.log': 'Log file for the sink which is installed into Remoting to intercept and authenticate Remoting calls.',
            'AttendantService.log': 'Debug log file for the MAIS service process.',
            'CSCache.log': 'Debug log file for the module maintaining a cache of the configuration settings read from Configuration Services.',
            'CSDatabases.log': 'Debug log file for module responsible for finding matching databases based off of timestamp/date.',
            'CSHolderADA.log': 'Debug log file containing data about the Configuration Services Holder plugin for ADA.',
            'DirectoryEngineAD.log': 'Debug log file for the module used to make queries to AD.',
            'Fetch.log': 'Debug log showing the results from the FETCH IMAP command. Only retrieves UID and Sequence number of message.',
            'IMAP.log': 'Debug log file showing the IMAP communication.',
            'IMAPDB.log': 'Debug log file for maintenance on the cache database.',
            'IMAPRemote.log': 'Debug log file for the configuration and connection to the IMAP server.',
            'IMAPServer.log': 'Debug log file for what the IMAP server is currently doing.',
            'RemotingPlugin.log': 'Debug log file for the Remoting plug-in used to start the other plug-ins which can be connected to by components in other MARC processes.',
            'ServerController.log': 'Debug log file showing the commands handled by remoting: start, restart, stop, etc.',
            'Sync.log': 'Debug log file for the synchronization intervals between the Active and All databases.',
            'SyncDetail.log': 'Debug log detailing each message that is synchronized.',
            'VssWriterSubscriber.log': 'Debug log file for the VSSWriterSubscriber module loaded by the IMAP service.'
        }
    },
    'MailboxRestore': {
        'description': 'Logs related to restoring mailboxes in Archiver.',
        'files': {
            'LocalizationProvider.log': 'Debug log file for localization of the MB Restore tool.',
            'MBRestore.log': 'Debug log file for the MB Restore tool.'
        }
    },
    'MAIS': {
        'description': 'Logs related to MAIS service processes and email management.',
        'files': {
            'AdaAuthentication.log': 'Debug log file for the module which provides an authentication mechanism for ADA with AD.',
            'AdaCache.log': 'Debug log file of the module which maintains a cache of information retrieved from AD by ADA.',
            'AdaInformation.log': 'Debug log file of the module used to retrieve information from AD.',
            'AttendantService.log': 'Debug log file for the MAIS service process.',
            'BixPlugin.log': 'Debug log file for the module which converts BIX files to .eml files in the MAIS\\Pickup folder, before they can be processed by MAIS.',
            'Configuration.log': 'Debug log file for the MAIS configuration.',
            'CSCache.log': 'Debug log file for the module maintaining a cache of the configuration settings read from Configuration Services – a Core Remoting component.',
            'CSHolderADA.log': 'Debug log file containing data about the Configuration Services Holder plugin for ADA.',
            'CSHolderHostplugin4.log': 'Debug log file containing data about the Configuration Services Holder plugin for HostPlugin.',
            'DirectoryEngineAD.log': 'Debug log file for the module used to make queries to AD.',
            'Enveloper.log': 'Debug log file of the module which processes the emails in the raw emails in the Pickup directory and saves them in the Queue directory.',
            'EnveloperDS.log': 'Debug log file of the module which processes the emails in the raw emails in the Pickup directory and saves them in the Queue directory.',
            'Lock.log': 'Debug log file for the MAIS lock – this is used to instruct the export tools to pause exporting emails since there are a lot of emails pending to be processed by MAIS.',
            'MsSql.log': 'Debug log file of the module used to access the Microsoft SQL databases when uploading the messages.',
            'RemotingPlugin.log': 'Debug log file for the Remoting plug-in used to start the other plug-ins which can be connected to by components in other MARC processes.',
            'Supervisor.log': 'Debug log file for the Supervisor which monitors various locations and setting the MAIS lock when required.',
            'Transfer.log': 'Debug log file for the module which transfers emails from the Queue folder to the databases via Store.',
            'VssWriterSubscriber.log': 'Debug log file for the VssWriterSubscriber module loaded by the MAIS service.',
            'Worker.log': 'Debug log file for the module which processes emails from the Pickup folder and makes them readily available for the Transfer module to be able to upload them to the correct database.'
        }
    },
    'MarcImportExport': {
        'description': 'Logs related to import and export processes.',
        'files': {
            'skipfail.log': 'Debug log file listing reasons and subject of skipped/failed emails when exporting emails using the Import Export tool.',
            'autodiscovery.log': 'Debug log file for AutoDiscovery information needed by the Import Export tool.',
            'BulkExport.log': 'Debug log file for the export from Archiver module.',
            'ExchPstExport.log': 'Debug log file for the export from Exchange/PST module.',
            'ExportUI.log': 'Debug log file for the Export UI.',
            'LacalizationProvider.log': 'Debug log file for localization of the Import Export tool.',
            'MainConfiguration.log': 'Debug log file for the Import Export tool configuration module.',
            'UAutoDisc.log': 'Debug log file used by the tool which detects the best available Microsoft Exchange Client Access server through EWS.'
        }
    },
    'Search': {
        'description': 'Logs related to search functionality.',
        'files': {
            'AdaAuthentication.log': 'Debug log file for the module which checks the information on the logged on user, and provides this information to the other modules so that the correct data is shown to the user e.g. if the configuration tab is shown, or that only the user’s emails are retrieved from the database.',
            'AdaCache.log': 'Debug log file of the module which maintains a cache of information retrieved from AD by ADA.',
            'AdaConfigurationM.log': 'Debug log file for the module which is used to read user information from the MARC configuration relating to authentication and Roles and Permissions.',
            'AdaConfigurationR.log': 'Same as AdaConfigurationL.log, however the R in the filename signifies that the module was used by modules in other processes.',
            'AdaInformation.log': 'Debug log file for the module which retrieves information from AD whenever it is required.',
            'AdaSink.log': 'Log file for the sink which is installed into Remoting to intercept and authenticate Remoting calls.',
            'AttendantService.log': 'Log file for the MARC Attendant service. This will show the loading and unloading of the various Attendant modules.',
            'CSCache.log': 'Debug log file for the module maintaining a cache of the configuration settings read from Configuration Services – a Core Remoting component.',
            'CSHolder*.log': 'Debug log file of the Configuration Services cache, which caches configuration to avoid extra calls to Core. This module may be loaded multiple times, and will log to multiple log files.',
            'DirectoryEngineAD.log': 'Log file of the module used when querying AD for user information. This module is used when a user tries to access to the MARC interface.',
            'FileWatcher.log': 'Debug log file for the module which triggers events every time a search request is made, thus avoiding merging sub-indexes at the time.',
            'GFI.Common.Tracing.log': 'Common debug log written by the gfi_log module.',
            'IndexAttachments.log': 'Debug log file for the module which is used to index text in attachments.',
            'IndexDataSource.log': 'Debug log file for the module used to retrieve data from the emails in order to index such data.',
            'IndexDecompress.log': 'Debug log file for the module which decompresses files from archives in order to index the contents of archives which can be indexed.',
            'IndexJob.log': 'Debug log file for the module that handles the index jobs which includes requesting the latest timestamp from the database, requesting emails from the database, requesting dtSearch to index data, and requesting Meta.Search.Firebird to store the DOCID to the meta.fdb database.',
            'IndexScheduler.log': 'Debug log file for the module which ensures that data gets indexed based on the schedule configured in MARC.',
            'IndexTextConverter.log': 'Debug log file for the module which converts text to UNICODE before it is indexed.',
            'IndexUtils.log': 'Logs the usage of our own "indexing utilities" such as cleaning the temp folder etc. This is done by the Indexer.',
            'JobQueue.log': 'Debug log file for the module which stores the Index Jobs.',
            'Management.log': 'Debug log file for the module which manages the indexes. This module ensures that multiple concurrent actions which may lead to the corruption of the indexes are not executed at the same time.',
            'Management_vss.log': 'Debug log file for the VSS operations happening in the Search Management module.',
            'Meta.Engine.Firebird.log': 'Debug log file for the module which writes data to meta.fdb.',
            'Meta.Engine.Firebird.Search.log': 'Debug log file for the module which reads data to meta.fdb.',
            'Meta.Engine.MsCeSql.log': 'Debug log file for the module which writes data to meta.sdf.',
            'Meta.Engine.MsCeSql.Search.log': 'Debug log file for the module which reads data to meta.sdf.',
            'Meta.log': 'Debug log file of the module which manages all the other modules involved in reading and writing data from meta database.',
            'MetaCache.log': 'Debug log file for the module which maintains the meta.fdb cache. This module takes care of adding items to the cache and has the logic to decide when to remove items from the cache.',
            'MetaCacheItem.log': 'Debug log file for the module which removes items from the meta database cache.',
            'RemotingPlugin.log': 'Debug log file for the Remoting plug-in used to start the other plug-ins which can be connected to by components in other MARC processes.',
            'SearchFilterGenarator.log': 'Logs the process of the generation of the search filter. This will help to determine what went wrong in the case of a user receiving emails which are not his.',
            'SearchInterface.log': 'Debug log file for the module which receives Rebuild Index requests.',
            'SearchLog.log': 'Used to check the amount of time taken by the Search module to retrieve a result.',
            'SearchManagement.log': 'Debug log file which contains logging of the management of the actual search operations such as handling of the search index cache.',
            'SearchQuery.log': 'Debug log file for the Remoting module which receives search requests from the ASPNET web application.',
            'SearchUtilities.log': 'Debug log file for Search Utilities, showing search filtering by user in the UI.',
            'VssWriterSubscriber.log': 'Debug log file for the VSSWriterSubscriber module loaded by the Search service.',
            'WordBrkShim.log': 'Debug log file for the module which is used to identify words in different languages. This module helps in the indexing of emails.'
        }
    },
    'Store': {
        'description': 'Logs related to data storage and retrieval.',
        'files': {
            'AdaAuthentication.log': 'Debug log file for the module which checks the information on the logged on user, and provides this information to the other modules so that the correct data is shown to the user e.g. if the configuration tab is shown, or that only the user’s emails are retrieved from the database.',
            'AdaCache.log': 'Debug log file of the module which maintains a cache of information retrieved from AD by ADA.',
            'AdaConfigurationM.log': 'Debug log file for the module which is used to read user information from the MARC configuration relating to authentication and Roles and Permissions.',
            'AdaConfigurationR.log': 'Same as AdaConfigurationL.log, however the R in the filename signifies that the module was used by modules in other processes.',
            'AdaInformation.log': 'Debug log file for the module which retrieves information from AD whenever it is required.',
            'AdaSink.log': 'Log file for the sink which is installed into Remoting to intercept and authenticate Remoting calls.',
            'ArchiveStoreManager.log': 'Log file for the automatic creation of archive stores based on date/time.',
            'AttendantService.log': 'Log file for the MARC Attendant service. This will show the loading and unloading of the various Attendant modules.',
            'AuditDataRetrieval.log': 'Debug log file for the AuditDataRetrieval Store Remoting plug-in. This plug-in will log any attempts to retrieve data from the Audit Database.',
            'AuditDataUpload.log': 'Debug log file for the AuditDataUpload Store Remoting plug-in. This plug-in will log attempts to save data to the Audit Database.',
            'AuditFactory.log': 'Debug log file of the module which provides a provider to any plugin that needs to make use of the Audit Database.',
            'AuditProviders.log': 'Debug log file for the module which acts as an interface to the Audit Database. Any interaction with the Audit Database will be logged in this debug log file.',
            'Common.Cache.log': 'Debug log file for the caching system used by the UpdatesNotifications Remoting Store module.',
            'CSCache.log': 'Debug log file for the module maintaining a cache of the configuration settings read from Configuration Services – a Core Remoting component.',
            'CSHelper.log': 'Configuration Services Helper debug log file.',
            'CSHolder*.log': 'Debug log file for the module which caches configuration information related to particular modules. There can be multiple debug log files starting with this name, indicating that the same module is used by multiple modules.',
            'DalEmailFactory.log': 'Debug log file for the DAL module which creates and maintains connections to the databases configured in MARC. These connections will be re-used as required whenever information needs to be written or read from the database. These connections are supplied to other components in MARC by the DALEamilFactoryHostPlugins.',
            'DalEmailFactoryHostPluginX.log': 'Debug log file of the DAL module which serves connections to modules which require a connection to the database. This module may be loaded by different components, and each time it is loaded, it will log to a new debug log file, appending a number at the end of the name of the file.',
            'DataStorageResolver.log': 'Debug log file of the module which checks what type of information needs to be archived with the database where such information will be archived. Currently only emails can be archived with MARC.',
            'DirectoryEngineAD.log': 'Log file of the module used when querying AD for user information. This module is used when a user tries to access to the MARC interface.',
            'DLEAgent.log': 'Debug log file for a Remoting module which is used to archive email data received from the Core service.',
            'EmailMessageGateway.log': 'Debug log file for the DAL module which is used to connect to the different types of databases. This is the module which retrieves data from the database, or which saves data to the database.',
            'EmailMessageMaintenance.log': 'Debug log file for the EmailMessageMaintenance module – the module which is started by the MaintenanceScheduler and which updates the updates cache, and which deletes message bodies for old emails.',
            'EmailMessageManipulation.log': 'Debug log file for the Remoting module which is used when the user adds or removes a label from an email stored in the database.',
            'EmailMessageMapper.log': 'Debug log file of the DAL component which converts email information found in the Queue folders into information (business objects) which can be understood by the rest of DAL. This information will then be used to create the information in the database.',
            'EmailMessageProvider*.log': 'Debug log file for the DAL module which stores or retrieves data from the database. This module can be loaded by different components, and each time it loads, it will log to a different log file.',
            'EmailMessageRetrieval.log': 'Debug log file for the Remoting module which is used to retrieve emails from the Archive Stores. EmailMessageRetrieval will not access the Archive Stores directly, but will make use of other components like EmailMessageMapper, EmailMessageGateway and EmailMessageProviderHostpluginX to retrieve the information from the database.',
            'EmailMessageUpload.log': 'Debug log file for the module which is used to upload the message to the database. This module is called directly by DLEAgent. This module calls the Retention module to write any retention information to the email, and will make use of DAL to upload the message.',
            'EmailSourceCache.log': 'Debug log for items contained in the source cache.',
            'ErrorsDal.log': 'Debug log file which contains errors for the Data Access Layer, normally underlining errors between the various database back ends, Firebird, SQL and SQL + NTFS and the Store service.',
            'MailInsightsReporting.log': 'Debug log file for the initialization of the MailInsights reporter.',
            'MailSplit.log': 'Debug log file for the module used to split an email e.g. when an attachment is downloaded by the user from the MARC UI.',
            'MaintenanceScheduler.log': 'Debug log file for the module which starts the email maintenance and the email retention processes as per the intervals specified in its configuration file.',
            'MAISEmlUpload.log': 'Debug log file for the Store module which receives requests from MAIS to archive emails.',
            'Management.log': 'Debug log file for the Management module which is used to create databases and verify the schema of new databases configured in MARC.',
            'ManagementFactory.log': 'Debug log file for loading the schema builder.',
            'ManagementProviders.log': 'Debug log file for testing connection to SQL server for archive stores.',
            'Marc.Hash.log': 'Debug log file for hashes generated for messages.',
            'NoMatch.log': 'Logs all requests from UMPolling to Store which have failed to match and email.',
            'RemotingPlugin.log': 'Debug log file for the Remoting plug-in used to start the other plugins which can be connected to by components in other MARC processes.',
            'Retention.log': 'Debug log file which assigns retention and categorization information to an email before it is saved to the database as per the categorization and retentions rules.',
            'RetentionMaintenance.log': 'Debug log file for the module which performs the email retention maintenance, and removes any emails from the database as per the retention policies.',
            'Retroretention.log': 'Log file that tracks the execution of a retro-retention policy.',
            'Statistics.log': 'Debug log file for getting the database version and statistics for the given GUID.',
            'StatisticsMaintenance.log': 'Debug log file maintenance performed on DB GUIDs in terms of the statistics ran.',
            'Updates.log': 'Debug log file for the Remoting module which is used to provide information on the latest updates to the MARC databases per database and per user.',
            'VssWriterSubscriber.log': 'Debug log file for the VSSWriterSubscriber module loaded by the Store service.'
        }
    },
    'VSS': {
        'description': 'Logs related to Volume Shadow Copy Service operations.',
        'files': {
            'AttendantService.log': 'Log file for the MARC Attendant service. This will show the loading and unloading of the various Attendant modules.',
            'VssWriter.log': 'Debug log file of the VssWriter module.',
            'VssWriterBridge.log': 'Debug log file for the VssWriter Bridge module.'
        }
    }
}